import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Aozora</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.container}>
            <div className={styles.top}>
                <div className="top-container">
                    <h1>Aozora Buds</h1>
                    <Image src="/happyvalley_logo.svg" alt="happyvalley_logo" width={100} height={100} />
                </div>
                <span className={styles.border}></span>
                <p>Welcome.<br />Please choose your preferred language.</p>
            </div>
            <div className={styles.btns}>
                <ul>
                    <li>
                        <Link href="/th/">แบบไทย</Link>
                        <Image src="/arrow.png" width={10} height={20} alt="arrow" />
                    </li>
                    <li>
                        <Link href="/en/">English</Link>
                        <Image src="/arrow.png" width={10} height={20} alt="arrow" />
                    </li>
                    <li>
                        <Link href="/de/">Deutsch</Link>
                        <Image src="/arrow.png" width={10} height={20} alt="arrow" />
                    </li>
                    <li>
                        <Link href="/ru/">Русский</Link>
                        <Image src="/arrow.png" width={10} height={20} alt="arrow" />
                    </li>
                    <li>
                        <Link href="/zh/">簡体中文</Link>
                        <Image src="/arrow.png" width={10} height={20} alt="arrow" />
                    </li>
                    <li>
                        <Link href="/ko/">한국어</Link>
                        <Image src="/arrow.png" width={10} height={20} alt="arrow" />
                    </li>
                    <li>
                        <Link href="/ja/">日本語</Link>
                        <Image src="/arrow.png" width={10} height={20} alt="arrow" />
                    </li>
                </ul>
            </div>
            <div className="bottom">
                <Image src="/aozora-logo.png" width={100} height={100} alt="aozora-logo" />
                <Image src="/qr-img.png" width={100} height={100} alt="QR-img" />
            </div>
        </div>
      </main>
    </>
  )
}
